name: Release App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            ext: .exe

          - goos: linux
            goarch: amd64
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod tidy

      - name: Build app
        run: |
          mkdir dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -ldflags="-s -w" \
          -o dist/site-blocker-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
